In [1]:
import os
from excelGen import excelOption

c:\users\gregg\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

In [2]:
tickers = ["SPY","XLK","MSFT"]
start_date = "2015-01-01"
end_date = None

data = excelOption(tickers, start_date, end_date)

bloomberg_functions = data.generateData()

bloomberg_functions["SPY"]

,SPY 3/20/15 C205,,SPY 4/17/15 C201,,SPY 5/15/15 C211,,SPY 6/19/15 C205,,SPY 7/17/15 C210,,...,SPY 6/19/20 C246,,SPY 7/17/20 C282,,SPY 8/21/20 C305,,SPY 9/18/20 C310,,SPY 10/16/20 C328,
0,"=BDH(""SPY 3/20/15 C205 Equity"",""PX_LAST"",20150...",,"=BDH(""SPY 4/17/15 C201 Equity"",""PX_LAST"",20150...",,"=BDH(""SPY 5/15/15 C211 Equity"",""PX_LAST"",20150...",,"=BDH(""SPY 6/19/15 C205 Equity"",""PX_LAST"",20150...",,"=BDH(""SPY 7/17/15 C210 Equity"",""PX_LAST"",20150...",,...,"=BDH(""SPY 6/19/20 C246 Equity"",""PX_LAST"",20200...",,"=BDH(""SPY 7/17/20 C282 Equity"",""PX_LAST"",20200...",,"=BDH(""SPY 8/21/20 C305 Equity"",""PX_LAST"",20200...",,"=BDH(""SPY 9/18/20 C310 Equity"",""PX_LAST"",20200...",,"=BDH(""SPY 10/16/20 C328 Equity"",""PX_LAST"",2020...",

In [3]:
bloomberg_functions["XLK"]

,XLK 3/20/15 C41,,XLK 4/17/15 C40,,XLK 5/15/15 C43,,XLK 6/19/15 C41,,XLK 7/17/15 C43,,...,XLK 6/19/20 C76,,XLK 7/17/20 C88,,XLK 8/21/20 C97,,XLK 9/18/20 C104,,XLK 10/16/20 C113,
0,"=BDH(""XLK 3/20/15 C41 Equity"",""PX_LAST"",201501...",,"=BDH(""XLK 4/17/15 C40 Equity"",""PX_LAST"",201502...",,"=BDH(""XLK 5/15/15 C43 Equity"",""PX_LAST"",201503...",,"=BDH(""XLK 6/19/15 C41 Equity"",""PX_LAST"",201504...",,"=BDH(""XLK 7/17/15 C43 Equity"",""PX_LAST"",201505...",,...,"=BDH(""XLK 6/19/20 C76 Equity"",""PX_LAST"",202004...",,"=BDH(""XLK 7/17/20 C88 Equity"",""PX_LAST"",202005...",,"=BDH(""XLK 8/21/20 C97 Equity"",""PX_LAST"",202006...",,"=BDH(""XLK 9/18/20 C104 Equity"",""PX_LAST"",20200...",,"=BDH(""XLK 10/16/20 C113 Equity"",""PX_LAST"",2020...",

In [4]:
bloomberg_functions["MSFT"]

,MSFT 3/20/15 C46,,MSFT 4/17/15 C41,,MSFT 5/15/15 C43,,MSFT 6/19/15 C40,,MSFT 7/17/15 C48,,...,MSFT 6/19/20 C152,,MSFT 7/17/20 C174,,MSFT 8/21/20 C182,,MSFT 9/18/20 C204,,MSFT 10/16/20 C216,
0,"=BDH(""MSFT 3/20/15 C46 Equity"",""PX_LAST"",20150...",,"=BDH(""MSFT 4/17/15 C41 Equity"",""PX_LAST"",20150...",,"=BDH(""MSFT 5/15/15 C43 Equity"",""PX_LAST"",20150...",,"=BDH(""MSFT 6/19/15 C40 Equity"",""PX_LAST"",20150...",,"=BDH(""MSFT 7/17/15 C48 Equity"",""PX_LAST"",20150...",,...,"=BDH(""MSFT 6/19/20 C152 Equity"",""PX_LAST"",2020...",,"=BDH(""MSFT 7/17/20 C174 Equity"",""PX_LAST"",2020...",,"=BDH(""MSFT 8/21/20 C182 Equity"",""PX_LAST"",2020...",,"=BDH(""MSFT 9/18/20 C204 Equity"",""PX_LAST"",2020...",,"=BDH(""MSFT 10/16/20 C216 Equity"",""PX_LAST"",202...",